### ISSUE TITLE
support embedded mode

### ISSUE THREAD

**Issue by nha** [7bridges-eu/clj-odbp#15]
orientdb.com/orientdb-embedded/
https://orientdb.com/docs/last/Embedded-Server.html

Not sure what it means with regards to serialization.
But it would help with experiments/tests and simplify deployments

**Comment by manuel-uberti** [comment]
Hi,

embedding the server doesn't really concern the driver. The main reason is we will need to provide OrientDB server jars as dependencies along with the driver.

We can devise an example project to show you how the driver works with OrientDB's embedded mode.
