### ISSUE TITLE
Add support to transactions

### ISSUE THREAD

**Issue by mdallastella** [7bridges-eu/clj-odbp#19]
~~Implement [REQUEST_TX_COMMIT](http://orientdb.com/docs/2.2/Network-Binary-Protocol.html#requesttxcommit) as described in the documentation.~~

Nope. Instead of this solution, we can use the BATCH feature, as OrientJS already [does](http://orientdb.com/docs/last/OrientJS-Transactions.html).

So we are going to implement a ```let```, a ```return``` and an ```execute-script``` function.
See [REQUEST_COMMAND](http://orientdb.com/docs/last/Network-Binary-Protocol.html#requestcommand) and [BATCH](http://orientdb.com/docs/last/SQL-batch.html).

**Comment by mdallastella** [comment]
Script support for REQUEST_COMMAND has been implemented. We should write some documentation about use scripts for transactions.

**Comment by manuel-uberti** [comment]
Documentation added in [README.md](https://github.com/7bridges-eu/clj-odbp/tree/develop#transactions).
