### ISSUE TITLE
Avoid negative rids on query result

### ISSUE THREAD

**Issue by manuel-uberti** [7bridges-eu/clj-odbp#3]
When we try to execute a select such as this one:
```
select @rid, name from Test
```
The result is something like the following:
```
{:_version 0 :_rid "#-2:0" :name "test"}
```

**Comment by mdallastella** [comment]
Negative rids are used on projections: the example query does not return a complete/valid record, so it can't be updated. Returning a negative rid (`#-2:n`) is a sort of safety measure.
Not a bug, it's a feature!
